cybercog/laravel-love

CHANGELOG.md, composer.json, tests/Unit/Console/Commands/RecountTest.php
=> Add Laravel 5.8 support

contracts/Reacter/Facades/Reacter.php, contracts/Reacterable/Models/Reacterable.php, src/Facades/Love.php, src/Reacter/Facades/Reacter.php, src/Reacterable/Models/Traits/Reacterable.php, tests/Unit/Reacter/Facades/ReacterTest.php, tests/Unit/Reacter/Models/ReacterTest.php, tests/Unit/Reacterable/Models/Traits/ReacterableTest.php
=> Add Reacter Facade

contracts/Reactable/Models/Reactable.php, contracts/Reactant/Facades/Reactant.php, src/Reactable/Models/Traits/Reactable.php, src/Reactant/Facades/Reactant.php, tests/Unit/Reactable/Models/Traits/ReactableTest.php, tests/Unit/Reactant/Facades/ReactantTest.php, tests/Unit/Reactant/Models/ReactantTest.php, tests/Unit/Reacterable/Models/Traits/ReacterableTest.php, tests/database/factories/ReactionTypeFactory.php
=> Add Reactant Facade

contracts/Reactant/Facades/Reactant.php, contracts/Reacter/Facades/Reacter.php, src/Reacter/Facades/Reacter.php, tests/Unit/Reactant/Facades/ReactantTest.php, tests/Unit/Reacter/Facades/ReacterTest.php
Adds missing methods from #59 & #62
=> Add missing methods to facades

contracts/Reactant/Facades/Reactant.php, contracts/Reacter/Facades/Reacter.php, src/Reactant/Facades/Reactant.php, src/Reacter/Facades/Reacter.php, tests/Unit/Reactant/Facades/ReactantTest.php, tests/Unit/Reacter/Facades/ReacterTest.php
Continue of #54 implementation.
Improvement of #59 & #62
=> Simplify facades API

contracts/Reactable/Models/Reactable.php, contracts/Reacterable/Models/Reacterable.php, src/Reactable/Models/Traits/Reactable.php, src/Reacterable/Models/Traits/Reacterable.php, tests/Unit/Reactable/Models/Traits/ReactableTest.php, tests/Unit/Reacterable/Models/Traits/ReacterableTest.php
Continue of #54 implementation.
Improvement of #59 & #62
=> Change facade getter methods prefix to `via`

CHANGELOG.md, config/love.php, database/migrations/2018_07_22_000100_create_love_reacters_table.php, database/migrations/2018_07_22_001000_create_love_reactants_table.php, database/migrations/2018_07_22_001500_create_love_reaction_types_table.php, database/migrations/2018_07_22_002000_create_love_reactions_table.php, database/migrations/2018_07_25_000000_create_love_reactant_reaction_counters_table.php, database/migrations/2018_07_25_001000_create_love_reactant_reaction_totals_table.php, src/LoveServiceProvider.php, src/Reactant/Models/Reactant.php, src/Reactant/ReactionCounter/Models/ReactionCounter.php, src/Reactant/ReactionTotal/Models/ReactionTotal.php, src/Reacter/Models/Reacter.php, src/Reaction/Models/Reaction.php, src/ReactionType/Models/ReactionType.php, src/Support/Database/Eloquent/Model.php, src/Support/Database/Migration.php
This PR implements @vesper8 proposal #61: ability to set custom database connection name for all package models & migrations.
=> Add configurable database connection

config/love.php, src/LoveServiceProvider.php
=> Add ability to ignore default migrations loading

CHANGELOG.md, src/Console/Commands/Recount.php, tests/Unit/Console/Commands/RecountTest.php
=> Change signature of Artisan love:recount command

CHANGELOG.md, contracts/Reaction/Exceptions/CannotChangeRate.php, contracts/Reaction/Exceptions/RateInvalid.php, contracts/Reaction/Models/Reaction.php, src/Reacter/Models/Reacter.php, src/Reaction/Models/Reaction.php, tests/Unit/Reacter/Facades/ReacterTest.php, tests/Unit/Reacter/Models/ReacterTest.php, tests/Unit/Reaction/Models/ReactionTest.php
=> Add changeRate method to Reaction

UPGRADING.md, src/Console/Commands/UpgradeV7ToV8.php
This PR adds debug information to automated migration artisan command and improves upgrade guide.
=> More informative v7 to v8 upgrade process

.gitignore, CHANGELOG.md, composer.json
This PR adds Laravel 6.x support.
=> Add Laravel v6 support

src/Support/Database/Stubs/AddForeignColumn.stub, src/Support/Database/Stubs/AddForeignNullableColumn.stub
=> Also drop foreign key before column

.styleci.yml, src/Console/Commands/SetupReactable.php, src/Console/Commands/SetupReacterable.php, src/Reaction/Models/Reaction.php, tests/Unit/Reaction/Models/ReactionTest.php
Fix StyleCI because Laravel changed imports order.
=> Fix StyleCI

src/Console/Commands/RegisterReactants.php, src/Console/Commands/RegisterReacters.php, tests/Stubs/Models/MorphMappedReactable.php, tests/Stubs/Models/MorphMappedReacterable.php, tests/TestCase.php, tests/Unit/Console/Commands/RegisterReactantsTest.php, tests/Unit/Console/Commands/RegisterReactersTest.php, tests/database/factories/BotFactory.php, tests/database/factories/ReactableWithMorphMap.php, tests/database/factories/ReacterableWithMorphMap.php, tests/database/migrations/2016_09_02_173301_create_morph_mapped_reactables_table.php, tests/database/migrations/2016_09_02_173301_create_morph_mapped_reacterables_table.php
=> Add console register commands tests

CHANGELOG.md, src/Reactant/Jobs/DecrementReactionAggregatesJob.php, src/Reactant/Jobs/IncrementReactionAggregatesJob.php, src/Reactant/Listeners/DecrementAggregates.php, src/Reactant/Listeners/IncrementAggregates.php
=> Make jobs class naming more explicit

CHANGELOG.md, src/Console/Commands/Recount.php, src/Console/Commands/RegisterReactants.php, src/Console/Commands/RegisterReacters.php
Console commands must return integer. 0 on success, 1 on fail.
=> Fix love:recount Artisan command return type

.phpstan.neon, .travis.yml, composer.json, src/Console/Commands/ReactionTypeAdd.php, src/Console/Commands/Recount.php, src/Console/Commands/RegisterReactants.php, src/Console/Commands/RegisterReacters.php, src/Console/Commands/SetupReactable.php, src/Console/Commands/SetupReacterable.php, src/Reactant/Facades/Reactant.php, src/Reactant/Jobs/RebuildReactionAggregatesJob.php, src/Reactant/Models/NullReactant.php, src/Reactant/Models/Reactant.php, src/Reactant/ReactionCounter/Models/NullReactionCounter.php, src/Reactant/ReactionCounter/Models/ReactionCounter.php, src/Reactant/ReactionCounter/Services/ReactionCounterService.php, src/Reactant/ReactionTotal/Models/NullReactionTotal.php, src/Reactant/ReactionTotal/Models/ReactionTotal.php, src/Reactant/ReactionTotal/Services/ReactionTotalService.php, src/Reacter/Facades/Reacter.php, src/Reacter/Models/NullReacter.php, src/Reacter/Models/Reacter.php, src/Reaction/Events/ReactionHasBeenAdded.php, src/Reaction/Events/ReactionHasBeenRemoved.php, src/Reaction/Models/Reaction.php, src/Reaction/Observers/ReactionObserver.php, src/ReactionType/Models/ReactionType.php, src/Support/Database/AddForeignColumnStub.php, src/Support/Database/Eloquent/Model.php, src/Support/Database/Migration.php
This PR adds PHPStan static analysis and starts errors fixing procedure.
On `--level=8` 224 errors were found.
After this PR:
> [ERROR] Found 174 errors
=> Add PHPStan

.phpstan.neon, composer.json, src/Console/Commands/RegisterReactants.php, src/Console/Commands/RegisterReacters.php, src/Console/Commands/UpgradeV5ToV6.php, tests/Unit/Reactable/Models/Traits/ReactableTest.php, tests/Unit/Reactant/Models/ReactantTest.php, tests/Unit/Reacter/Facades/ReacterTest.php, tests/Unit/Reaction/Models/ReactionTest.php, tests/Unit/ReactionType/Models/ReactionTypeTest.php
Changes done only in tests and private methods of console commands. Not breaking.
PHPStan level increased from 0 to 1.
=> Increase PHPStan level from 0 to 1

contracts/Reaction/Exceptions/ReactionAlreadyExists.php, src/Reacter/Models/Reacter.php
Move exception message out from the model to the exception method.
=> Add ReactionAlreadyExists::ofType method

.travis.yml, CHANGELOG.md, composer.json
This PR adds PHP 8.x support to Laravel Love
=> Add PHP 8.x support

CHANGELOG.md, src/Console/Commands/ReactionTypeAdd.php, src/Console/Commands/Recount.php, src/Console/Commands/RegisterReactants.php, src/Console/Commands/RegisterReacters.php, src/Console/Commands/SetupReactable.php, src/Console/Commands/SetupReacterable.php, src/Console/Commands/UpgradeV5ToV6.php, src/Console/Commands/UpgradeV7ToV8.php
Optimize console commands by using static `$defaultName` property by being able to find what command to call without instantiating all of them.
=> Optimize console commands

.github/workflows/tests.yml, CHANGELOG.md, composer.json, tests/TestCase.php, tests/Unit/Reaction/Events/ReactionHasBeenAddedTest.php, tests/Unit/Reaction/Events/ReactionHasBeenRemovedTest.php
Lowest version is 10.1.3 because of the migration issues.
=> Add Laravel v10 support

CHANGELOG.md, UPGRADING.md, src/Reactant/Models/Reactant.php, src/Reactant/ReactionCounter/Models/ReactionCounter.php, src/Reactant/ReactionTotal/Models/ReactionTotal.php, src/Reacter/Models/Reacter.php, src/Reaction/Models/Reaction.php, src/ReactionType/Models/ReactionType.php, tests/Unit/Reaction/Models/ReactionTest.php
- Follow up #247
- Follow up #248
=> Refactor Eloquent Model Attributes casting
