CHANGELOG.md, README.md, UPGRADING.md, contracts/Likeable/Models/Likeable.php, contracts/Liker/Models/Liker.php, src/Likeable/Models/Traits/Likeable.php, src/Likeable/Services/LikeableService.php, src/Liker/Models/Traits/Liker.php, tests/Stubs/Models/User.php, tests/Unit/Console/Commands/Recount.php, tests/Unit/Like/Models/LikeTest.php, tests/Unit/Like/Observers/LikeObserverTest.php, tests/Unit/LikeCounter/Models/LikeCounterTest.php, tests/Unit/Likeable/Events/LikeableWasDislikedTest.php, tests/Unit/Likeable/Events/LikeableWasLikedTest.php, tests/Unit/Likeable/Events/LikeableWasUndislikedTest.php, tests/Unit/Likeable/Events/LikeableWasUnlikedTest.php, tests/Unit/Likeable/Models/Traits/LikeableTest.php, tests/Unit/Likeable/Observers/LikeableObserverTest.php, tests/Unit/Likeable/Services/LikeableServiceTest.php, tests/Unit/Liker/Exceptions/InvalidLikerTest.php, tests/Unit/Liker/Models/Traits/LikerTest.php
The main goal of the release: make API more explicit and give an ability to extend it in future.
This PR solves #2 by adding postfix `By` to all `Likeable` methods names where Liker is passed as argument.
=> Release v5

src/Providers/LoveServiceProvider.php
I made this PR because Installation instructions don't work as intended.
`php artisan migrate` should work without publishing first.
=> load migrations in provider boot method

CHANGELOG.md, database/migrations/2018_07_22_002000_create_love_reactions_table.php, database/migrations/2018_07_25_000000_create_love_reactant_reaction_counters_table.php, database/migrations/2018_07_25_001000_create_love_reactant_reaction_totals_table.php
Remove single column indexes for foreign keys because `foreign` method creates them already.
=> Removed duplicating indexes for foreign keys

.travis.yml, CHANGELOG.md, README.md, composer.json, tests/TestCase.php, tests/Unit/Console/Commands/Recount.php
Fixes tests and updates environment.
Continue #48 & #43 
PHP7.0 tests are disabled because there is no other way to add Laravel 5.8 support.
=> Fix Laravel 5.8 support in v5

CHANGELOG.md, src/Console/Commands/SetupReactable.php, src/Console/Commands/SetupReacterable.php, tests/Unit/Console/Commands/SetupReactableTest.php, tests/Unit/Console/Commands/SetupReacterableTest.php
Artisan commands `love:setup-reacterable` & `love:setup-reactable` should receive model as option, not as argument.
=> Fix artisan setup commands options

CHANGELOG.md, contracts/Reacter/Facades/Reacter.php, src/Reacter/Facades/Reacter.php, tests/Unit/Reacter/Facades/ReacterTest.php
This PR fixes boolean check methods names.
Despite the fact it's a breaking change - I'm publishing it as hotfix because it was designed and documented as `hasReactedTo` & `hasNotReactedTo`, but I copy-pasted `isReactedTo` & `isNotReactedTo` by mistake. *Publishing releases late night is bad.*
=> Fix Reacter facade boolean method names

src/Reactant/Models/NullReactant.php, src/Reacter/Models/NullReacter.php, tests/Unit/Reactant/Models/NullReactantTest.php, tests/Unit/Reacter/Models/NullReacterTest.php
Fixes #76
Returns `Illuminate\Support\Collection` instead or `array` in `NullReactant` & `NullReacter` iterable methods.
=> Return Collection instead of array in iterable Null objects methods

CHANGELOG.md, contracts/Reactant/Models/Reactant.php, contracts/Reacter/Models/Reacter.php, src/Reactant/Facades/Reactant.php, src/Reactant/Models/NullReactant.php, src/Reactant/Models/Reactant.php, src/Reacter/Facades/Reacter.php, src/Reacter/Models/NullReacter.php, src/Reacter/Models/Reacter.php, tests/Unit/Reactant/Models/NullReactantTest.php, tests/Unit/Reactant/Models/ReactantTest.php, tests/Unit/Reacter/Models/NullReacterTest.php, tests/Unit/Reacter/Models/ReacterTest.php
Resolves #63 
1. Replace `isReactedTo` & `isReactedToWithType` with single `hasReactedTo` method.
2. Replace `isNotReactedTo` & `isNotReactedToWithType` with single `hasNotReactedTo` method.
Before:
```php
$reacter->isReactedTo(Reactant);
$reacter->isReactedToWithType(Reactant, ReactionType);
$reacter->isNotReactedTo(Reactant);
$reacter->isNotReactedToWithType(Reactant, ReactionType);
```
After:
```php
$reacter->hasReactedTo(Reactant, ?ReactionType);
$reacter->hasNotReactedTo(Reactant, ?ReactionType);
```
1. Replace `isReactedBy` & `isReactedByWithType` with single `isReactedBy` method.
2. Replace `isNotReactedBy` & `isNotReactedByWithType` with single `isNotReactedBy` method.
Before:
```php
$reactant->isReactedBy(Reacter);
$reactant->isReactedByWithType(Reacter, ReactionType); …
```
=> Merge similar boolean methods

CHANGELOG.md, src/Console/Commands/ReactionTypeAdd.php, tests/Unit/Console/Commands/ReactionTypeAddTest.php
Resolves #82 
This command will create `Like` type with weight equal to `1`:
```sh
php artisan love:reaction-type-add --name=Like --weight=1
```
This command is similar to command above:
```sh
php artisan love:reaction-type-add --weight=1 --name=Like
```
This command will interactively ask for `name` and after it will create type with weight equal to `1`:
```sh
php artisan love:reaction-type-add --weight=1
```
This command will interactively ask for `weight` and after it will create type with name equal to `Like`:
```sh
php artisan love:reaction-type-add --name=Like
```
=> Change signature of Artisan reaction-type-add command

CHANGELOG.md, composer.json, tests/Unit/Console/Commands/ReactionTypeAddTest.php, tests/Unit/Console/Commands/RecountTest.php, tests/Unit/Console/Commands/SetupReactableTest.php, tests/Unit/Console/Commands/SetupReacterableTest.php
Laravel 5.6 has reached End of Life. Dropping it's support to start using default attribute values introduced in Laravel 5.7.
=> Drop Laravel 5.6 support

CHANGELOG.md, UPGRADING.md, contracts/ReactionType/Models/ReactionType.php, database/migrations/2018_07_22_001500_create_love_reaction_types_table.php, src/Console/Commands/ReactionTypeAdd.php, src/Console/Commands/UpgradeV7ToV8.php, src/Reaction/Models/Reaction.php, src/ReactionType/Models/ReactionType.php, tests/Unit/Console/Commands/ReactionTypeAddTest.php, tests/Unit/Console/Commands/RecountTest.php, tests/Unit/Reactable/Models/Traits/ReactableTest.php, tests/Unit/Reactant/ReactionCounter/Services/ReactionCounterServiceTest.php, tests/Unit/Reactant/ReactionTotal/Services/ReactionTotalServiceTest.php, tests/Unit/Reaction/Models/ReactionTest.php, tests/Unit/Reaction/Observers/ReactionObserverTest.php, tests/Unit/ReactionType/Models/ReactionTypeTest.php, tests/database/factories/ReactionTypeFactory.php
=> Rename ReactionType weight to mass

CHANGELOG.md, UPGRADING.md, src/Reactable/Models/Traits/Reactable.php, tests/Unit/Reactable/Models/Traits/ReactableTest.php
Replace `scopeWhereReactedBy` & `scopeWhereReactedByWithType` with single `scopeWhereReactedBy` method.
Before:
```php
Comment::whereReactedBy(Reactant);
Comment::whereReactedByWithType(Reactant, ReactionType);
```
After:
```php
Comment::whereReactedBy(Reactant, ?ReactionType);
```
=> Merge whereReactedByWithType method to whereReactedBy

CHANGELOG.md, database/migrations/2018_07_25_000000_create_love_reactant_reaction_counters_table.php, database/migrations/2018_07_25_001000_create_love_reactant_reaction_totals_table.php, src/Console/Commands/UpgradeV7ToV8.php, src/LoveServiceProvider.php, src/Reactant/ReactionCounter/Models/ReactionCounter.php, src/Reactant/ReactionCounter/Observers/ReactionCounterObserver.php, src/Reactant/ReactionTotal/Models/ReactionTotal.php, src/Reactant/ReactionTotal/Observers/ReactionTotalObserver.php, tests/Unit/Reactant/ReactionCounter/Observers/ReactionCounterObserverTest.php, tests/Unit/Reactant/ReactionTotal/Observers/ReactionTotalObserverTest.php
Make only one place where default attribute values are declared.
`ReactionCounter` & `ReactionTotal` attributes `count` & `weight` default values defined on database layer and in `$attributes` array of the model.
`ReactionCounter` & `ReactionTotal` model classes will have constants for each attribute default value:
- `ReactionCounter::DEFAULT_COUNT`
- `ReactionCounter::DEFAULT_WEIGHT`
- `ReactionTotal::DEFAULT_COUNT`
- `ReactionTotal::DEFAULT_WEIGHT`
=> Move counters default attributes values to application level

CHANGELOG.md, contracts/Reactant/Facades/Reactant.php, src/Reactant/Facades/Reactant.php, tests/Unit/Reactant/Facades/ReactantTest.php
=> Allow null Reacterable in Reactant facade

CHANGELOG.md, UPGRADING.md, src/Console/Commands/UpgradeV5ToV6.php, src/Console/Commands/UpgradeV7ToV8.php, src/Reactable/Models/Traits/Reactable.php, tests/Unit/Reactable/Models/Traits/ReactableTest.php
=> Simplify Reactable scopes API

src/Console/Commands/ReactionTypeAdd.php, src/Console/Commands/Recount.php, src/Console/Commands/SetupReactable.php, src/Console/Commands/SetupReacterable.php, src/Console/Commands/UpgradeV5ToV6.php, src/Console/Commands/UpgradeV7ToV8.php
Instead of multi-line `$signature` string define command signature as `$name` string and `getOptions()` method which returns array of the available options.
This changes are fully backward compatible because all commands classes are `final`.
=> Change Artisan commands signature definition format

CHANGELOG.md, composer.json, contracts/Reactable/Exceptions/ReactableInvalid.php, contracts/Reactant/Exceptions/ReactantInvalid.php, contracts/Reactant/ReactionCounter/Exceptions/ReactionCounterDuplicate.php, contracts/Reactant/ReactionCounter/Exceptions/ReactionCounterInvalid.php, contracts/Reactant/ReactionTotal/Exceptions/ReactionTotalDuplicate.php, contracts/Reactant/ReactionTotal/Exceptions/ReactionTotalInvalid.php, contracts/Reacter/Exceptions/ReacterInvalid.php, contracts/Reaction/Exceptions/RateOutOfRange.php, contracts/ReactionType/Exceptions/ReactionTypeInvalid.php, src/Reaction/Models/Reaction.php
Exception `Cog\Contracts\Love\Reaction\Exceptions\RateOutOfRange` shouldn't depend on concrete `Cog\Laravel\Love\Reaction\Models\Reaction` class.
If you implemented `Cog\Contracts\Love\Reaction\Models\Reaction` interface by yourself - this change will be breaking. It will be done in minor release because it's fixing contracts dependencies issue.
=> Fix contract dependency from concrete implementation

CHANGELOG.md, contracts/Reacter/Models/Reacter.php, src/Reacter/Models/NullReacter.php, src/Reacter/Models/Reacter.php
For the consistency reason change `float $rate = null` parameter to `?float $rate = null` in `Reacter` models.
Despite the fact this PR changes the contract - it will be released in minor version because it's fully backward compatible.
=> Fix Reacter model's hasReactedTo & hasNotReactedTo methods signature

.gitignore, composer.json, tests/TestCase.php
This PR adds Laravel 6.x support to Laravel Love v5
=> Add Laravel v6 support to Love v5

CHANGELOG.md, database/migrations/2018_07_22_000100_create_love_reacters_table.php, database/migrations/2018_07_22_001000_create_love_reactants_table.php, database/migrations/2018_07_22_001500_create_love_reaction_types_table.php, database/migrations/2018_07_22_002000_create_love_reactions_table.php, database/migrations/2018_07_25_000000_create_love_reactant_reaction_counters_table.php, database/migrations/2018_07_25_001000_create_love_reactant_reaction_totals_table.php, src/Console/Commands/SetupReactable.php, src/Console/Commands/SetupReacterable.php, src/Support/Database/Migration.php
Resolves #116 
@vesper8 found that Migration's `getConnection()` method is used only for resolving if connection supports schema transactions, but never used in migration itself.
```php
protected function runMigration($migration, $method)
{
$connection = $this->resolveConnection(
$migration->getConnection()
);
$callback = function () use ($migration, $method) {
if (method_exists($migration, $method)) {
$this->fireMigrationEvent(new MigrationStarted($migration, $method));
$migration->{$method}();
$this->fireMigrationEvent(new MigrationEnded($migration, $method));
}
};
$this->getSchemaGrammar($connection)->supportsSchemaTransactions()
&& $migration->withinTransaction
? $connection->transaction($callback)
: $callback();
}
```
So I've added protected `$schema` property with configured …
=> Fix custom connection in database migrations

CHANGELOG.md, src/Reactant/Jobs/DecrementAggregatesJob.php, src/Reactant/Jobs/IncrementAggregatesJob.php, src/Reactant/Listeners/DecrementAggregates.php, src/Reactant/Listeners/IncrementAggregates.php
First part of configurable events behavior concept #145 
Extracted logic from `Cog\Laravel\Love\Reactant\Listeners\IncrementAggregates` listener to `Cog\Laravel\Love\Reactant\Jobs\IncrementAggregatesJob`
Extracted logic from `Cog\Laravel\Love\Reactant\Listeners\DecrementAggregates` listener to `Cog\Laravel\Love\Reactant\Jobs\DecrementAggregatesJob`
=> Extract logic from Reactant Listeners to Reactant Jobs

CHANGELOG.md, composer.json, src/LoveEventServiceProvider.php, src/LoveServiceProvider.php, tests/TestCase.php
Second part of configurable events behavior concept #145 
In this PR I've extracted event listeners registering from `Cog\Laravel\Love\LoveServiceProvider` to separate `Cog\Laravel\Love\LoveEventServiceProvider` class.
Resolves #139
=> Extract event listeners registering to LoveEventServiceProvider

CHANGELOG.md, src/Console/Commands/Recount.php, src/Reactant/Jobs/RebuildAggregatesJob.php, src/Reactant/Jobs/RebuildReactionAggregatesJob.php
Resolves #137
Resolves #138
Hey @vesper8! This PR should fix both of your issues. It fixes recounting when counters & totals are not yet exists and allows you to call the command separately from the console command.
For example:
```php
RebuildReactionAggregatesJob::dispatch($reactant, $reactionType);
```
Now it's using queues, so if you want to call it synchronously you could call it on `sync` connection:
```php
RebuildReactionAggregatesJob::dispatch($reactant, $reactionType)
->onConnection('sync');
```
Console command will have queue connection option too:
```shell script
$ php artisan love:recount --model="App\User" --queue-connection=redis
```
To keep backward compatibility `sync` connection will be used by default until the next major version.
What do you think about it?
=> Extract Reactant reactions recounting logic to RebuildReactionAggregatesJob

src/Console/Commands/Recount.php, src/Reactant/Facades/Reactant.php, src/Reactant/Jobs/DecrementReactionAggregatesJob.php, src/Reactant/Jobs/IncrementReactionAggregatesJob.php, src/Reactant/Jobs/RebuildReactionAggregatesJob.php, src/Reactant/Listeners/DecrementAggregates.php, src/Reactant/Listeners/IncrementAggregates.php, src/Reacter/Facades/Reacter.php, src/Reacter/Models/NullReacter.php
Fixing consistency:
- Each interface import should have `*Contract` postfix.
- Interfaces which are implemented by class should start from the new line.
=> Code style fixes for typehints

src/Reaction/Observers/ReactionObserver.php
Avoid usage of `event` global helper method.  This PR resolves event dispatcher in `__construct`.
=> Use DI instead of global event helper method

CHANGELOG.md, src/Reactant/Listeners/DecrementAggregates.php, src/Reactant/Listeners/IncrementAggregates.php
Queue is not required in listeners because all the logic was moved (#146) to Job classes which are already using queues. This will speed up counters & totals creation and decrease load of your queues.
=> Remove redundant queues from Reactant listeners

CHANGELOG.md, config/love.php, database/migrations/2018_07_22_000100_create_love_reacters_table.php, database/migrations/2018_07_22_001000_create_love_reactants_table.php, database/migrations/2018_07_22_001500_create_love_reaction_types_table.php, database/migrations/2018_07_22_002000_create_love_reactions_table.php, database/migrations/2018_07_25_000000_create_love_reactant_reaction_counters_table.php, database/migrations/2018_07_25_001000_create_love_reactant_reaction_totals_table.php, src/Support/Database/Eloquent/Model.php
Proof of concept https://github.com/cybercog/laravel-love/issues/164#issuecomment-622610209
Resolves #163
Define any custom table name in `config/love.php` file
```php
'storage' => [
'database' => [
'connection' => env('DB_CONNECTION', 'mysql'),
'tables' => [
'love_reacters' => 'custom_reacters',
'love_reactants' => 'custom_reactants',
'love_reaction_types' => 'data.reaction_types',
],
],
],
```
Table names with `null` value will use values from Model's `$table` class property.
Different schema/database could be defined for cross-schema queries by adding its name with dot on the end before the table name, eg. `data.reaction_types`. More details read in #163
=> Make model table names configurable

src/Reactant/Jobs/DecrementReactionAggregatesJob.php, src/Reactant/Jobs/IncrementReactionAggregatesJob.php
I'm using Laravel Job events to determine when `IncrementReactionAggregatesJob` or `DecrementReactionAggregatesJob` is processed.
<pre>Queue::after(function (JobProcessed $event) {
dd(unserialize($event->job->payload()['data']['command']));
});</pre>
This PR allows easily accessing the private properties in the job class.
=> Add getters for aggregates job

CHANGELOG.md, composer.json
This PR fixes:
- [CVE-2021-21263](https://github.com/advisories/GHSA-3p32-j457-pg5x)
- [GHSA-x7p5-p2c9-phvg](https://github.com/advisories/GHSA-x7p5-p2c9-phvg)
=> Fix CVE-2021-21263 & GHSA-x7p5-p2c9-phvg vulnerabilities

.travis.yml, CHANGELOG.md, composer.json
Followup #196 
Laravel 6.0 requires PHP >= 7.2.5
=> Drop PHP 7.1 support

CHANGELOG.md, src/Reacterable/Models/Traits/Reacterable.php, tests/Unit/Reacterable/Models/Traits/ReacterableTest.php
This MR adds `whereReactedTo` & `whereNotReactedTo` query scopes to Reacterable trait to find all Reacterable models who reacted to the Reactable model. This concept was born after discussion with @vesper8 in #181
```php
$article = Article::whereKey(1)->firstOrFail();
$usersReactedToArticle = User::whereReactedTo($article);
```
```php
$article = Article::whereKey(1)->firstOrFail();
$likeReactionType = ReactionType::fromName('Like');
$usersLikedTheArticle = User::whereReactedTo($article, $likeReactionType);
```
This MR doesn't have tests yet and I'm not sure if we should add it to the minor release.
=> Add query scopes to Reacterable trait

CHANGELOG.md, src/Console/Commands/SetupReactable.php, src/Console/Commands/SetupReacterable.php, src/Support/Database/Stubs/AddForeignColumn.stub, src/Support/Database/Stubs/AddForeignNullableColumn.stub, tests/Unit/Console/Commands/SetupReactableTest.php, tests/Unit/Console/Commands/SetupReacterableTest.php
- Resolves #140 
- Console command `love:setup-reactable` generates migration with nullable column `love_reactant_id` by default
- Console command `love:setup-reactable` option `--nullable` replaced with `--not-nullable`
- Console command `love:setup-reacterable` generates migration with nullable column `love_reacter_id` by default
- Console command `love:setup-reacterable` option `--nullable` replaced with `--not-nullable`
=> Make love_reactant_id & love_reacter_id columns nullable by default

CHANGELOG.md, src/Console/Commands/Recount.php
In PR #148 we've introduced option `--queue-connection=` to run command using the queue. By default it was using `sync` connection to keep backward compatibility.
```shell
php artisan love:recount --model="App\User" --queue-connection=sync
```
In v9 it should use default queue connection from the application config when option is `null` or empty.
=> Console command love:recount use default queue connection

contracts/Reactant/Facades/Reactant.php, contracts/Reactant/Models/Reactant.php, src/Reactant/Facades/Reactant.php, src/Reactant/Models/NullReactant.php, src/Reactant/Models/Reactant.php, tests/Unit/Reactant/Facades/ReactantTest.php, tests/Unit/Reactant/Models/NullReactantTest.php, tests/Unit/Reactant/Models/ReactantTest.php
Feature request appeared in issue:
- #237
This is implementation of the Solution №2 from the discussion:
- https://github.com/cybercog/laravel-love/discussions/239#discussioncomment-5501195
Method  `\Cog\Contracts\Love\Reactant\Facades::getReactions` signature changed:
```php
public function getReactions(
Reacterable | null $reacterable = null,
): iterable;
```
Usage:
```php
// Get all reactions the post received
$allReactionsOnPost = $post->viaLoveReactant()->getReactions();
// Get reactions the post received from the user
$userReactionsOnPost = $post->viaLoveReactant()->getReactions($user);
```
Method `\Cog\Contracts\Love\Reactant\Models\Reactant::getReactionsBy` method introduced:
```php
public function getReactionsBy(
Reacter $reacter,
): iterable;
```
Usage:
```php
// Get reactions …
```
=> Add fetch reactions by Reacterable model

CHANGELOG.md, src/Reaction/Models/Reaction.php, src/Reaction/Observers/ReactionObserver.php, tests/Unit/Reactant/ReactionCounter/Models/ReactionCounterTest.php, tests/Unit/Reactant/ReactionTotal/Models/ReactionTotalTest.php, tests/Unit/Reaction/Models/ReactionTest.php
=> Remove ReactionObserver::creating method

database/migrations/2018_07_25_000000_create_love_reactant_reaction_counters_table.php, database/migrations/2018_07_25_001000_create_love_reactant_reaction_totals_table.php
There are two migrations (`love_reactant_reaction_counters` and `love_reactant_reaction_totals`) that use hardcoded table names instead of dynamically fetching table names with model's `getTable()`. This causes an error when running the migrations as those tables do not exist. This PR solves this issue by just replacing the hardcoded table names by the model's `getTable()`.
=> fix: use table names from config file
